DROP TABLE IF EXISTS phones CASCADE;
DROP TABLE IF EXISTS versions CASCADE;
DROP TABLE IF EXISTS years CASCADE;
DROP TABLE IF EXISTS prices CASCADE;
CREATE TABLE phones(id SERIAL PRIMARY KEY NOT NULL)
CREATE versions (
  id SERIAL PRIMARY KEY NOT NULL,
  phone_id INTEGER REFERENCES phones(id) ON DELETE CASCADE,
  name_id VARCHAR(75)
)
CREATE TABLE years(
  id SERIAL PRIMARY KEY NOT NULL,
  version_id INTEGER REFERENCES versions(id) ON DELETE CASCADE,
  year_id INTEGER,
)
CREATE TABLE prices(
  id SERIAL PRIMARY KEY NOT NULL,
  years_id INTEGER REFERENCES years(id) ON DELETE CASCADE,
)
